### ISSUE TITLE
Unable to decode file on Windows 10

### ISSUE THREAD

**Issue by tomrwaller** [fragtastic/cis-benchmark-to-csv#1]
When I try to run this in Windows 10 against a PDF benchmark saved to .txt I get the following error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3785: character maps to <undefined>`

I've tried saving the text file with UTF8 encoding but the error still occurs.

**Comment by fragtastic** [comment]
@tomrwaller Give it a try with the latest commit. I've been using this on MacOS and Linux without issue so far.
I forgot about this project since last year. There's additional scripts which output to Excel XLSX directly now too.

If there's still an issue if you could provide some more details I'd be appreciated.
OS Version, Python version, which CIS benchmark PDF you're using, etc.

**Comment by tomrwaller** [comment]
Thanks for getting back to me on this. I have tried with the latest commit but I am still getting the error below.

```
Parsing .\CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark_v1.8.1.txt
Writing to .\CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark_v1.8.1.txt.csv
Traceback (most recent call last):
  File ".\cisConv.py", line 134, in <module>
    parseText(args.inputFile)
  File ".\cisConv.py", line 64, in parseText
    for line in inFile:
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1689: character maps to <undefined>
```

**Comment by benderase** [comment]
I'm having the same issue. 
I'm Using Macos Catalina- Ver. 10.15.5

/usr/bin/env python3 -V
Python 3.6.1

CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.0.0.pdf 

Error I'm getting:
Parsing CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.0.0.pdf
Writing to CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.0.0.pdf.csv
Traceback (most recent call last):
  File "./cisConv.py", line 134, in <module>
    parseText(args.inputFile)
  File "./cisConv.py", line 64, in parseText
    for line in inFile:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte

**Comment by fragtastic** [comment]
@benderase This doesn't take a PDF input directly.
You need to dump the text from it first.

**Comment by fragtastic** [comment]
Closing stale issue. If persists with the latest version reopen.
