### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by vish1980** [fragtastic/cis-benchmark-to-csv#10]
Hi 

I am getting the following issue when running the script 

C:\Python30>python.exe cis2csv.py "C:\Users\visha\Desktop\New folder\CIS_Microsoft_Windows_Server_2019_RTM_Release_1809_Benchmark_v1.1.0.pdf"
Traceback (most recent call last):
  File "cis2csv.py", line 1, in <module>
    from cisconverter import CISConverterCSV
  File "C:\Python30\cisconverter\__init__.py", line 69
    logging.info(f'Parsing {self.args.inputFilePath}')

Please advise how this can be resolved as I need the excel sheet quite quickly 

regards

Vish

**Comment by fragtastic** [comment]
Only acceptable input is text, not pdf
