### ISSUE TITLE
script error 

### ISSUE THREAD

**Issue by vitor-fagundes** [fragtastic/cis-benchmark-to-csv#11]
I am trying to convert CIS, but I have this error. 

![erro](https://user-images.githubusercontent.com/74776867/107817503-047ed200-6d55-11eb-803b-d59be2f3645d.PNG)

can you help me?

**Comment by fragtastic** [comment]
This should be fixed in an update.
I'll reference the update here when it's uploaded.

**Comment by fragtastic** [comment]
Update pushed. Closing issue.
