### ISSUE TITLE
Output excel wrongly split rows

### ISSUE THREAD

**Issue by legendOfZelda** [fragtastic/cis-benchmark-to-csv#16]
### Problem
cis2excel.py converts some CIS benchmarks incorrectly.

### Steps to reproduce
The incorrect output was observed for the following CIS benchmarks:

- cis2excel.py -l ERROR CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0.txt
- cis2excel.py -l ERROR CIS_Microsoft_365_Foundations_Benchmark_v1.3.0.txt

where the .txt files were first obtained by exporting to text with Adobe Acrobat DC, as mentioned in the README.
The output Excels have the following issues:

- CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0.xlsx: CIS Controls 1.3, 1.23, 2.12, 3.5, 5.1.1, 5.1.3 are split into multiple rows
- CIS_Microsoft_365_Foundations_Benchmark_v1.3.0.xlsx: CIS Control 1.1.2 is split into multiple rows and the last Control 7.13 is missing

**Comment by fragtastic** [comment]
This should be fixed now.

Azure Foundations 1.4.0:
- Total lines: 9777
- Written Rows: 115
Azure Foundations 1.3.0:
- Total Lines: 6789
- Written Rows: 111
