### ISSUE TITLE
Usage tips

### ISSUE THREAD

**Issue by nathanpinotti** [fragtastic/cis-benchmark-to-csv#26]
Hi
I'm trying to convert Microsoft365 CIS Benchmark with no luck. I have the python module required but nothing happens when I run:

`.\cis2excel.py C:\temp\CIS_Microsoft_365_Foundations_Benchmark_v3.1.0.txt`
or
`.\cis2excel.py --sheetname cis365.xlsx C:\temp\CIS_Microsoft_365_Foundations_Benchmark_v3.1.0.txt`

Any tip/guidance is much appreciated!

Regards

**Comment by fragtastic** [comment]
Please provide a detailed log/output.
