### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ghost** [fragtastic/cis-benchmark-to-csv#3]
I've been getting the error `TypeError: 'NoneType' object is not subscriptable` when trying to run the script against some benchmarks but not all.  I am running this on Ubuntu 20.04 with Python 3.8.2.  

I open the PDF using Adobe Acrobat copy/paste into a text file and run the script against that text file. For example, with Windows Server 2016 and Windows Server 2019 the script completes but when run against the Ubuntu benchmark, the error above is received.  I believe this is due to inconsistencies with the way the benchmarks are formatted.

Example:  
Windows --> 1.1.1 (Level Number) Title (Scored | Not Scored)
Ubuntu --> 1.1.1 Title (Automated | Manual)

Ubuntu does not provide a level1/level2 and it doesn't use Scored/Not Scored which the regex doesn't accommodate for.  I'll try to do some testing on my end to figure this out but your regex skills may be a little better than mine!

**Comment by fragtastic** [comment]
Thanks for pointing that out.
Yeah, CIS are pretty inconsistent overall.
The regex needs `Automated` and `Manual` added.

I'll push an update to add those.

**Comment by fragtastic** [comment]
Working for me now. 👍

<img width="862" alt="image" src="https://user-images.githubusercontent.com/420314/97931262-15fe1a00-1d22-11eb-8171-8af55fdb9351.png">
