### ISSUE TITLE
Not getting the dump right

### ISSUE THREAD

**Issue by berthou** [fragtastic/cis-benchmark-to-csv#7]
Hi !
Thanks for work ! I'd like to use your tool but it doesn't work as expected for me.
example on CIS_Ubuntu_Linux_20.04_LTS_Benchmark_v1.0.0.pdf :
```
INFO:root:Writing to ubuntu.csv

INFO:root:Parsing ubuntu.txt

INFO:root:Total lines: 14737

INFO:root:Written Rows: 9
```

how do you dump the text ? 
I'm on ubuntu

**Comment by fragtastic** [comment]
I only have a MacOS system that I run this on.

Steps I take are as follows:
1: Use Adobe Acrobat Reader / DC
2: Select All text
3: Copy
4: Open new text document
5: Paste text
