### ISSUE TITLE
UnicodeDecodeErro

### ISSUE THREAD

**Issue by vitor-fagundes** [fragtastic/cis-benchmark-to-csv#8]
The error is triggered when I will convert the benchmark to both CSV and Excel. 
Can someone help me?
Follows the error image
![erro](https://user-images.githubusercontent.com/74776867/99806300-98f1e380-2b1c-11eb-9d91-2e7b5cf9e87b.PNG)

**Comment by fragtastic** [comment]
@vitor-fagundes This is for text (.txt file) dumped from the PDF, not the actual PDF.
